typography_spectrum: 0.9873395247850567
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.73800468002446
  lightness: 0.590916698332876
  saturation: 0.9382801258470863
  rhythmicContrast: 0.32227143202908337
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.5803093628492206
analytics:
  google: null
  facebook: null
  twitter: null
name: 'http://ashavose.blogspot.com/'
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Mr. Rochester
description: A sexy Jane Eyre Remake
purpose: []
